apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dirsrv
  name: dirsrv-external-svc
spec:
  ports:
  - name: dirsrv-nonsecure
    port: 3390
    protocol: TCP
    targetPort: 3390
    nodePort: 30390
  selector:
    app: dirsrv
  type: NodePort
status:
  loadBalancer: {}
