apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dirsrv
  name: dirsrv-internal-svc
spec:
  clusterIP: None
  ports:
  - name: dirsrv-nonsecure
    port: 3390
    protocol: TCP
    targetPort: 3390
  selector:
    app: dirsrv
  type: ClusterIP
status:
  loadBalancer: {}